import { jsPDF } from 'jspdf'
import html2canvas from 'html2canvas'

interface PDFGeneratorOptions {
    title: string
    element: HTMLElement
}

export async function generatePDF(options: PDFGeneratorOptions): Promise<Blob> {
    const { title, element } = options

    // Create PDF
    const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
    })

    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()
    const margin = 20
    const contentWidth = pageWidth - (margin * 2)

    // Capture the editor content
    const canvas = await html2canvas(element, {
        scale: 2, // Higher scale for better quality
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
        windowWidth: element.scrollWidth, // Ensure full width is captured
    })

    const imgData = canvas.toDataURL('image/png')
    const imgWidth = contentWidth
    const imgHeight = (canvas.height * imgWidth) / canvas.width

    let heightLeft = imgHeight
    let position = 0
    let page = 1

    // Add header to first page
    addHeader(pdf, title, pageWidth, margin)
    position = 40 // Start content after header

    // Add first page content
    pdf.addImage(imgData, 'PNG', margin, position, imgWidth, imgHeight)
    heightLeft -= (pageHeight - 40 - margin) // Subtract space used on first page

    // Add footer to first page
    addFooter(pdf, 1)

    // Add subsequent pages if needed
    while (heightLeft > 0) {
        position = heightLeft - imgHeight + margin // Adjust position for next page
        // Actually, for standard image splitting in jsPDF:
        // We need to add a new page and draw the image shifted up

        pdf.addPage()
        page++

        // Calculate position to draw the image so the next chunk is visible
        // The image is drawn at a negative y-coordinate to show the lower parts
        const shift = -(pageHeight * (page - 1)) + 40 // Adjust for header space on first page? 
        // Simpler approach: Just slice the canvas or accept standard splitting
        // For now, let's just add the image again with an offset

        pdf.addImage(imgData, 'PNG', margin, -(pageHeight - margin) * (page - 1) + 40, imgWidth, imgHeight)

        addFooter(pdf, page)
        heightLeft -= pageHeight
    }

    return pdf.output('blob')
}

function addHeader(pdf: jsPDF, title: string, pageWidth: number, margin: number) {
    // Blue background
    pdf.setFillColor(37, 99, 235)
    pdf.rect(0, 0, pageWidth, 25, 'F')

    // Brand text
    pdf.setTextColor(255, 255, 255)
    pdf.setFontSize(18)
    pdf.setFont('helvetica', 'bold')
    pdf.text('AdarshabaniNXT', pageWidth / 2, 15, { align: 'center' })

    // Document title
    pdf.setTextColor(0, 0, 0)
    pdf.setFontSize(20)
    pdf.setFont('helvetica', 'bold')
    pdf.text(title, margin, 35)

    // Divider line
    pdf.setDrawColor(200, 200, 200)
    pdf.line(margin, 38, pageWidth - margin, 38)
}

function addFooter(pdf: jsPDF, pageNum: number) {
    const pageHeight = pdf.internal.pageSize.getHeight()
    const pageWidth = pdf.internal.pageSize.getWidth()

    pdf.setFontSize(9)
    pdf.setTextColor(100, 100, 100)

    pdf.text(
        `Page ${pageNum}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
    )

    pdf.text(
        `Generated by AdarshabaniNXT - ${new Date().toLocaleDateString()}`,
        pageWidth / 2,
        pageHeight - 5,
        { align: 'center' }
    )
}
